def getPUList():
    return [
        "PU1",
        "PU2",
        "PU3",
        "PU4",
        "PU7",
        "PU8",
        "PU9",
        "PU10",
        "PU11",
        "PU12",
        "PU13",
        "PU14",
        "PU15",
        "PU16",
        "PU17",
        "PU20",
        "PU25",
        "PU26",
        "PU29",
        "PU34",
        "PU39",
        "PU40",
        "PU42",
        "PU43",
        "PU44",
        "PU53",
        "PU63",
        "STAFF",
        "PU18",
        "PU19",
        "PU21",
        "PU22",
        "PU23",
        "PU24",
        "PU27",
        "PU28",
        "PU30",
        "PU31",
        "PU32",
        "PU33",
        "PU35",
        "PU36",
        "PU37",
        "PU38",
        "PU41",
        "PU48",
        "PU50",
        "PU51",
        "PU52",
        "PU60",
        "PU61",
        "PU64",
        "PU72",
        "PU73",
        "PU74",
        "PU75",
        "PU99",
        "NONSTAFF",
        "GROSS",
        "CREDIT",
        "NET",
    ]


def getPHs():
    return ["PH11", "PH14", "PH15"]


def getPHsMap():
    return {
        "PH11": {
            "rowRange": list(range(5, 9)),
            "rowMap": ["CAP", "CAP(CH)", "SF", "TOTAL"],
        },
        "PH14": {
            "rowRange": list(range(10, 12)),
            "rowMap": ["CAP", "TOTAL"],
        },
        "PH15": {
            "rowRange": list(range(13, 16)),
            "rowMap": ["CAP", "CAP(RVNL)", "TOTAL"],
        },
    }
