def puMap():
    return {
        "PU1": "Pay",
        "PU2": "DA",
        "PU3": "PLB",
        "PU4": "HRA",
        "PU7": "Transport allowance",
        "PU8": "NPS",
        "PU9": "Wages of casual labour",
        "PU10": "Kilometer allowance",
        "PU11": "Overtime allowance",
        "PU12": "Night duty allowance",
        "PU13": "Other allowances",
        "PU14": "Fees and honoraria",
        "PU15": "Transfer allowance",
        "PU16": "Travelling expenses",
        "PU17": "Air Travel Expense sanctioned in lieu of privilege passes",
        "PU20": "Leave encashment",
        "PU25": "Children education allowance (CEA)",
        "PU26": "Medical reimbursement",
        "PU29": "Remuneration to Re-engaged officials",
        "PU34": "POH-Wages: Home",
        "PU39": "Air Travel (Domestic)",
        "PU40": "Air Travel (Foreign)",
        "PU42": "Arrear Payments-Pay",
        "PU43": "Arrear Payments-DA",
        "PU44": "Arrear Payments-Allowances other than DA",
        "PU53": "All India Leave Travel Concession (AILTC)",
        "PU63": "POH-Wages: Foreign",
        "PU18": "Office Expenses",
        "PU19": "Rental for P & T",
        "PU21": "Advertising Expenses",
        "PU22": "Utilities(excluding electricity)",
        "PU23": "Rental for office equipment (other than Data Processing)",
        "PU24": "Printing and Stationery",
        "PU27": "Material from Stock",
        "PU28": "Material-Direct Purchase",
        "PU30": "Cost of electrical energy",
        "PU31": "Fuel other than Traction",
        "PU32": "Contractual payments",
        "PU33": "Transfer of debits/credits",
        "PU35": "POH-Material: Home",
        "PU36": "Excise duty paid/payable",
        "PU37": "Customs duty paid/payable",
        "PU38": "Sales tax paid/payable",
        "PU41": "Value Added Tax (VAT)",
        "PU48": "Customs duty paid/payable",
        "PU50": "Cost of computer hardware/software",
        "PU51": "Cost of computer consumables",
        "PU52": "Laptop procured by officers ",
        "PU60": "Fuel from stock – Home Railway locomotives fuelled by foreign railway",
        "PU61": "GTKMs debits/ credits",
        "PU64": "POH-Material: Foreign",
        "PU72": "Central GST (CGST)",
        "PU73": "State GST (SGST)",
        "PU74": "Union Terrotory GST (UTGST)",
        "PU75": "Integrated GST (IGST)",
        "PU99": "Other Expenses (Misc.)",
    }


def summaryMap():
    return {
        "D-TRACTION": "Diesel traction",
        "E-TRACTION": "Electric traction",
        "E-OFFICE": "Electricity office",
        "HSD-CIVIL": "HSD for track macines",
        "HSD-GEN": "HSD for Gensets",
        "LEASE": "Lease and other debits",
        "IRFA": "IRFA debits",
        "COACH-C": "Coach sanitation",
        "STATION-C": "Station sanitation",
        "COLONY-C": "Colony sanitation",
    }
